language: java
dist: trusty
jdk: oraclejdk8
git:
  depth: false
addons:
  sonarcloud:
    organization: "seleniumcontrol"
    token:
      secure: "1f65ee2e32309caf60fcd576fd7c9dca57c9c2f0"
    branches:
      - master
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- git fetch --unshallow
  - mvn clean -U package
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=seleniumcontrol
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"