language: java
dist: trusty
jdk: oraclejdk12
install: true
addons:
  sonarcloud:
    organization: "d3f8a5336ce9588e797e9a71f16a14997b5949856daf7e11f94a1ff158"
    token:
      secure: "bb125257eb44d0169e71ce42b0e2bac005fcd6cd"
    branches:
      - master
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jesuslnv_SeleniumControl
#cache:
#  directories:
#    - "$HOME/.m2/repository"
#    - "$HOME/.sonar/cache"