language: java
#dist: trusty

#jdk:
#  - oraclejdk12

script:
  #- mvn clean -U package
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jesuslnv_SeleniumControl

#addons:
#  sonarcloud:
#    organization: "seleniumcontrol"
#    token:
#      secure: "c96ce45335355638bf63f0c12369a97354ab893f"
#      branches:
#        - master
#c96ce45335355638bf63f0c12369a97354ab893f
#dqpwrrb5Knr7p0v7_ovXPg